version: '3.8'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./docker/fpm/Dockerfile
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
        PHP_VERSION: ${PHP_VERSION:-8.5}
    volumes:
      - .:/var/www/

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT:-8080}:80
    volumes:
      - .:/var/www:rw
    depends_on:
      - php-fpm

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
       - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
